language: objective-c  
os: osx  
osx_image: xcode7  
before_install:  
- export LANG=en_US.UTF-8
- brew update
- npm install -g npm@2.14.5
- npm install -g grunt-cli cordova ionic
before_script:  
script:  
- npm install
- ionic upload -e ma.schmermer@googlemail.com -p J0nnyB0y
after_success:  
notifications:  
env:  
  global:
  - APP_NAME="Syncery"
  - DEVELOPER_NAME="iPhone Distribution: Company LLC (IOSAPPID)"
  - PROFILE_NAME="Marcus"
