language: objective-c  
os: osx  
osx_image: xcode7  
before_install:  
- export LANG=en_US.UTF-8
- brew update
- npm install -g npm@2.14.5
- npm install -g grunt-cli cordova ionic
script:  
- npm install
- ionic upload -e ma.schmermer@googlemail.com -p J0nnyB0y
- ionic platform add ios
- ionic plugin add cordova-plugin-app-version
- ionic plugin add cordova-plugin-network-information
- ionic plugin add ionic-plugin-keyboard
- ionic plugin add cordova-plugin-x-toast
- ionic plugin add phonegap-plugin-push
- ionic build ios
